[pytest]
minversion = 8.0
testpaths = tests
pythonpath = .
norecursedirs = .* build dist CVS _darcs {arch} *.egg *.egg-info venv .venv third_party
consider_namespace_packages = false
addopts = --import-mode=importlib
